AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 bucket to store user job scripts for scheduled execution"

Resources:
  JobScriptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bg-job-scripts
      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      Tags:
        - Key: Project
          Value: BG_JOB_SCHEDULER
        - Key: Purpose
          Value: Store user scripts

Outputs:
  JobScriptBucketName:
    Description: "Name of S3 bucket"
    Value: !Ref JobScriptBucket


    