AWSTemplateFormatVersion: "2010-09-09"
Description: "SQS Queue and DLQ for Background Job Scheduler"

Resources:

  JobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bg-job-dlq
      MessageRetentionPeriod: 1209600  

      Tags:
        - Key: Project
          Value: BG_JOB_SCHEDULER
        - Key: Purpose
          Value: Failed Jobs


  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bg-job-queue
      VisibilityTimeout: 300   

      RedrivePolicy:
        deadLetterTargetArn: !GetAtt JobDLQ.Arn
        maxReceiveCount: 3

      Tags:
        - Key: Project
          Value: BG_JOB_SCHEDULER
        - Key: Purpose
          Value: Job Processing

  EventBridgeToSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref JobQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt JobQueue.Arn

Outputs:

  JobQueueUrl:
    Description: "Main SQS Queue URL"
    Value: !Ref JobQueue

  JobQueueArn:
    Description: "Main SQS Queue ARN"
    Value: !GetAtt JobQueue.Arn

  JobDLQArn:
    Description: "Dead Letter Queue ARN"
    Value: !GetAtt JobDLQ.Arn
