version = 0.1

[default.deploy.parameters]
stack_name = "background-job-worker"
resolve_s3 = true
s3_prefix = "background-job-worker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "JobTableName=\"Job_Records\" LogBucketName=\"bg-logs-bucket\" QueueArn=\"arn:aws:sqs:ap-south-1:344776058261:bg-job-queue\" DlqArn=\"arn:aws:sqs:ap-south-1:344776058261:bg-job-dlq\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
